sudo: false

language: python

python:
  - "3.3"

install:
  - pip install flake8
  - pip install pep257

script:
  - flake8 . --max-line-length=80
  - pep257 . --ignore=D202 --ignore=D211

notifications:
  email: false
